# Generated by Django 3.2.20 on 2023-09-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_munites',
            new_name='time_minutes',
        ),
    ]
